# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Bagatron.RemoteDeck
PackageVersion: 0.4.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: RemoteDeck.exe
  PortableCommandAlias: remotedeck
Commands:
- remotedeck
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Bagatron/RemoteDeck/releases/download/v0.4.0/RemoteDeck-0.4.0-win-x64.zip
  InstallerSha256: 2CB5E0615464176D699986C32BD897F1DF79EA274372BBD8068218C48855D874
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-10-08
